# Generated by Django 4.1.4 on 2022-12-29 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(help_text='10 digit number', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Postal Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('alley', models.CharField(max_length=50, null=True, verbose_name='Alley')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='No')),
                ('floor', models.CharField(max_length=50, null=True, verbose_name='Floor')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('id_number', models.CharField(help_text='10 digit number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='National Number')),
                ('mobile', models.CharField(help_text='10 digit number without 0 at first', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Mobile')),
                ('phone', models.CharField(help_text='10 digit number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone')),
                ('image', models.ImageField(default='images/users/default.jpg', upload_to='images/users', verbose_name='Profile Image')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='Area(m2)')),
                ('phone', models.BooleanField(verbose_name='Phone')),
                ('parking', models.BooleanField(verbose_name='Parking')),
                ('contract_type', models.CharField(choices=[('m', 'Mortgage'), ('r', 'Rent'), ('s', 'Sale')], max_length=1, verbose_name='Contract Type')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('Mortgage_price', models.FloatField(null=True, verbose_name='Mortgage Price')),
                ('rent_price', models.FloatField(null=True, verbose_name='Rent Price')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_owner', to='users.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sh_tenant', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_room', models.IntegerField(verbose_name='Number of Rooms')),
                ('area', models.FloatField(verbose_name='Area(m2)')),
                ('phone', models.BooleanField(verbose_name='Phone')),
                ('parking', models.BooleanField(verbose_name='Parking')),
                ('pool', models.BooleanField(verbose_name='Pool')),
                ('contract_type', models.CharField(choices=[('m', 'Mortgage'), ('r', 'Rent'), ('s', 'Sale')], max_length=1, verbose_name='Contract Type')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('Mortgage_price', models.FloatField(null=True, verbose_name='Mortgage Price')),
                ('rent_price', models.FloatField(null=True, verbose_name='Rent Price')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_owner', to='users.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_tenant', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_room', models.IntegerField(verbose_name='Number of Rooms')),
                ('area', models.FloatField(verbose_name='Area(m2)')),
                ('story', models.IntegerField(verbose_name='Story')),
                ('phone', models.BooleanField(verbose_name='Phone')),
                ('parking', models.BooleanField(verbose_name='Parking')),
                ('elevator', models.BooleanField(verbose_name='Elevator')),
                ('pool', models.BooleanField(verbose_name='Pool')),
                ('contract_type', models.CharField(choices=[('m', 'Mortgage'), ('r', 'Rent'), ('s', 'Sale')], max_length=1, verbose_name='Contract Type')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('Mortgage_price', models.FloatField(null=True, verbose_name='Mortgage Price')),
                ('rent_price', models.FloatField(null=True, verbose_name='Rent Price')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_owner', to='users.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_tenant', to='users.user')),
            ],
        ),
    ]
