# Generated by Django 4.1.4 on 2022-12-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_alley_alter_address_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='Mortgage_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Mortgage Price'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rent_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Rent Price'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_tenant', to='users.user'),
        ),
        migrations.AlterField(
            model_name='house',
            name='Mortgage_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Mortgage Price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Rent Price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h_tenant', to='users.user'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Mortgage_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Mortgage Price'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rent_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Rent Price'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sh_tenant', to='users.user'),
        ),
    ]
