# Generated by Django 4.1.4 on 2023-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apartment_image_house_image_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, default='images/apartments/default.jpg', null=True, upload_to='apartments/', verbose_name='Apartment Image'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, default='images/houses/default.jpg', null=True, upload_to='houses/', verbose_name='House Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='images/shops/default.jpg', null=True, upload_to='shops/', verbose_name='Shop Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/users/default.jpg', upload_to='users/', verbose_name='Profile Image'),
        ),
    ]
