# Generated by Django 4.1.4 on 2022-12-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(auto_now=True, verbose_name='Contract Date')),
                ('expire', models.DateField(verbose_name='Expire Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tenant', to='users.user', verbose_name='Tenant/Buyer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_owner', to='users.user', verbose_name='Owner')),
            ],
        ),
    ]
